//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace app.ServiceReferenceLength {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET/", ConfigurationName="ServiceReferenceLength.lengthUnitSoap")]
    public interface lengthUnitSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.webserviceX.NET/ChangeLengthUnit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginChangeLengthUnit(double LengthValue, app.ServiceReferenceLength.Lengths fromLengthUnit, app.ServiceReferenceLength.Lengths toLengthUnit, System.AsyncCallback callback, object asyncState);
        
        double EndChangeLengthUnit(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webserviceX.NET/")]
    public enum Lengths {
        
        /// <remarks/>
        Angstroms,
        
        /// <remarks/>
        Nanometers,
        
        /// <remarks/>
        Microinch,
        
        /// <remarks/>
        Microns,
        
        /// <remarks/>
        Mils,
        
        /// <remarks/>
        Millimeters,
        
        /// <remarks/>
        Centimeters,
        
        /// <remarks/>
        Inches,
        
        /// <remarks/>
        Links,
        
        /// <remarks/>
        Spans,
        
        /// <remarks/>
        Feet,
        
        /// <remarks/>
        Cubits,
        
        /// <remarks/>
        Varas,
        
        /// <remarks/>
        Yards,
        
        /// <remarks/>
        Meters,
        
        /// <remarks/>
        Fathoms,
        
        /// <remarks/>
        Rods,
        
        /// <remarks/>
        Chains,
        
        /// <remarks/>
        Furlongs,
        
        /// <remarks/>
        Cablelengths,
        
        /// <remarks/>
        Kilometers,
        
        /// <remarks/>
        Miles,
        
        /// <remarks/>
        Nauticalmile,
        
        /// <remarks/>
        League,
        
        /// <remarks/>
        Nauticalleague,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface lengthUnitSoapChannel : app.ServiceReferenceLength.lengthUnitSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChangeLengthUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ChangeLengthUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public double Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class lengthUnitSoapClient : System.ServiceModel.ClientBase<app.ServiceReferenceLength.lengthUnitSoap>, app.ServiceReferenceLength.lengthUnitSoap {
        
        private BeginOperationDelegate onBeginChangeLengthUnitDelegate;
        
        private EndOperationDelegate onEndChangeLengthUnitDelegate;
        
        private System.Threading.SendOrPostCallback onChangeLengthUnitCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public lengthUnitSoapClient() {
        }
        
        public lengthUnitSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public lengthUnitSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public lengthUnitSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public lengthUnitSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<ChangeLengthUnitCompletedEventArgs> ChangeLengthUnitCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult app.ServiceReferenceLength.lengthUnitSoap.BeginChangeLengthUnit(double LengthValue, app.ServiceReferenceLength.Lengths fromLengthUnit, app.ServiceReferenceLength.Lengths toLengthUnit, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChangeLengthUnit(LengthValue, fromLengthUnit, toLengthUnit, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        double app.ServiceReferenceLength.lengthUnitSoap.EndChangeLengthUnit(System.IAsyncResult result) {
            return base.Channel.EndChangeLengthUnit(result);
        }
        
        private System.IAsyncResult OnBeginChangeLengthUnit(object[] inValues, System.AsyncCallback callback, object asyncState) {
            double LengthValue = ((double)(inValues[0]));
            app.ServiceReferenceLength.Lengths fromLengthUnit = ((app.ServiceReferenceLength.Lengths)(inValues[1]));
            app.ServiceReferenceLength.Lengths toLengthUnit = ((app.ServiceReferenceLength.Lengths)(inValues[2]));
            return ((app.ServiceReferenceLength.lengthUnitSoap)(this)).BeginChangeLengthUnit(LengthValue, fromLengthUnit, toLengthUnit, callback, asyncState);
        }
        
        private object[] OnEndChangeLengthUnit(System.IAsyncResult result) {
            double retVal = ((app.ServiceReferenceLength.lengthUnitSoap)(this)).EndChangeLengthUnit(result);
            return new object[] {
                    retVal};
        }
        
        private void OnChangeLengthUnitCompleted(object state) {
            if ((this.ChangeLengthUnitCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChangeLengthUnitCompleted(this, new ChangeLengthUnitCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChangeLengthUnitAsync(double LengthValue, app.ServiceReferenceLength.Lengths fromLengthUnit, app.ServiceReferenceLength.Lengths toLengthUnit) {
            this.ChangeLengthUnitAsync(LengthValue, fromLengthUnit, toLengthUnit, null);
        }
        
        public void ChangeLengthUnitAsync(double LengthValue, app.ServiceReferenceLength.Lengths fromLengthUnit, app.ServiceReferenceLength.Lengths toLengthUnit, object userState) {
            if ((this.onBeginChangeLengthUnitDelegate == null)) {
                this.onBeginChangeLengthUnitDelegate = new BeginOperationDelegate(this.OnBeginChangeLengthUnit);
            }
            if ((this.onEndChangeLengthUnitDelegate == null)) {
                this.onEndChangeLengthUnitDelegate = new EndOperationDelegate(this.OnEndChangeLengthUnit);
            }
            if ((this.onChangeLengthUnitCompletedDelegate == null)) {
                this.onChangeLengthUnitCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChangeLengthUnitCompleted);
            }
            base.InvokeAsync(this.onBeginChangeLengthUnitDelegate, new object[] {
                        LengthValue,
                        fromLengthUnit,
                        toLengthUnit}, this.onEndChangeLengthUnitDelegate, this.onChangeLengthUnitCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override app.ServiceReferenceLength.lengthUnitSoap CreateChannel() {
            return new lengthUnitSoapClientChannel(this);
        }
        
        private class lengthUnitSoapClientChannel : ChannelBase<app.ServiceReferenceLength.lengthUnitSoap>, app.ServiceReferenceLength.lengthUnitSoap {
            
            public lengthUnitSoapClientChannel(System.ServiceModel.ClientBase<app.ServiceReferenceLength.lengthUnitSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginChangeLengthUnit(double LengthValue, app.ServiceReferenceLength.Lengths fromLengthUnit, app.ServiceReferenceLength.Lengths toLengthUnit, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = LengthValue;
                _args[1] = fromLengthUnit;
                _args[2] = toLengthUnit;
                System.IAsyncResult _result = base.BeginInvoke("ChangeLengthUnit", _args, callback, asyncState);
                return _result;
            }
            
            public double EndChangeLengthUnit(System.IAsyncResult result) {
                object[] _args = new object[0];
                double _result = ((double)(base.EndInvoke("ChangeLengthUnit", _args, result)));
                return _result;
            }
        }
    }
}
